Add solution for Hw2
NevinTure/java-fintech-2024 pull request #2
Opened 2024-09-04 09:58 UTC by NevinTure

2024-09-06 16:44 UTC, engarik requested changes
Хорошо, что добавил интерфейс.
Хотелось бы:
1. Увидеть пример и результат использования, хотя бы в main методе
2. Добавить логгирование с уровнями warn и debug (требования задания)

2024-09-06 18:29 UTC, NevinTure commented
Исправил

2024-09-11 18:27 UTC, engarik commented on src/test/java/edu/java/XMLCityParserTest.java
> +import static org.assertj.core.api.Assertions.assertThat;
Статические импорты луше выносить отдельно, можешь у себя в idea настроить форматирование, чтобы он сам так делал
https://google.github.io/styleguide/javaguide.html#s3.3.3-import-ordering-and-spacing

2024-09-11 18:28 UTC, engarik commented
Принято, можно мерджить ✅

2024-09-11 18:30 UTC, merged